### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by zeratulmdq** [gionkunz/chartist-plugin-threshold#1]
Inside readme.md you have the following:

```
.ct-area.ct-threshold-above {
    stroke: #f05b4f;
}

.ct-area.ct-threshold-below {
    stroke: #59922b;
}
```

"stroke" should be changed to "fill" in both lines. It's fixed in the sample-styles.scss file but not in the docs, I spent four hours figuring out what was wrong with my chart code haha. 

A pull request for this seemed like too much.

BTW, great job with chartist.js!

**Comment by gionkunz** [comment]
Hey there! Thanks for the isse... crap.. I've fixed this in the example CSS but then missed the readme :-/ . Thanks for that and sorry you wasted your time!

**Comment by gionkunz** [comment]
I've updated the readme. Cheers!
